const ActionType = Object.freeze({
  SET_INITIAL_STATE: 'General/SET_INITIAL_STATE',
  SET_LOADING_INITIAL_STATE: 'Churches/SET_LOADING_INITIAL_STATE',
  SET_FETCHING: 'Churches/SET_FETCHING',
  ADD_TO_CHURCHES: 'Churches/ADD_TO_CHURCHES',
  UPDATE_CHURCH: 'Churches/UPDATE_CHURCH',
  DELETE: 'Churches/DELETE',
  UPDATE_COMPLETE: 'Churches/UPDATE_COMPLETE'
})

export default ActionType
