const ActionType = Object.freeze({
  SET_USERS: 'Users/SET_USERS',
  SET_FILTER: 'Users/SET_FILTER',
  COMPLETE_LOADING: 'Users/COMPLETE_LOADING',
  ADD_TO_USERS: 'Users/ADD_TO_USERS',
  UPDATE_USER: 'Users/UPDATE_USER',
  REMOVE_USER: 'Users/REMOVE_USER',
  UPDATE_FILTER: 'Users/UPDATE_FILTER',
  CLOSE_USERS_FILTER: 'Users/CLOSE_USERS_FILTER',
  OPEN_USERS_FILTER: 'Users/OPEN_USERS_FILTER'
})

export default ActionType
